version: 0.1

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - ls -al
      - aws s3 cp --recursive dist/ s3://$BUCKET_NAME/
      - zip blog.zip ./*
      - aws s3 cp blog.zip s3://$BUCKET_NAME/blog.zip
