version: 0.2

phases:
  install:
    commands:
      - echo update npm...
      - npm update -g npm
      - n v16
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - yarn build
      - cp ecosystem.json dist/ecosystem.json
  post_build:
    commands:
      - ls -al
      - aws s3 cp --recursive dist/ s3://$BUCKET_NAME/
      - zip blog.zip ./*
      - aws s3 cp blog.zip s3://$BUCKET_NAME/blog.zip
