version: '3.8'
services:
  education-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: education-server
    restart: always
    ports:
      - 8000:8000

    env_file:
      - .env
