version: 0.2
env:
  variables:
    BUCKET_NAME: ${BUCKET_NAME}
phases:
  install:
    commands:
      - echo ${BUCKET_NAME}
      - echo update npm...
      - npm update -g npm
      - n v16
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - yarn build
      - cp ecosystem.json dist/ecosystem.json
artifacts:
  files:
    - 'node_modules/**/*'
    - 'dist/**/*'
    - 'env/*'
    - 'scripts/**/*'
    - 'prisma/**/*'
    - 'package.json'
    - 'appspec.yml'
cache:
  paths:
    - 'node_modules/**/*'
    - 'env/*'
